server:
  port: 4871
  servlet:
    context-path: /sg
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password: zxcv123321AZ
  profiles:
    active:
      - prod
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
# mybatis-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration-properties:
    STATE_NO: 0
    STATE_YES: 1
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: ASSIGN_ID
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true

logging:
  level:
    com:
      baomidou:
        mybatisplus=DEBUG: